/* 
 * Switch Database REST API
 *
 * Switch API is the primary endpoint of data sevices and Switch DB's platform. You can do adding, editing, deleting or listing data works to your database with query operations by using this low-level API based on HTTP.
 *
 * OpenAPI spec version: 1.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Body struct {

	// List name.
	List string `json:"list,omitempty"`

	// Item count.
	Count int32 `json:"count,omitempty"`

	// Page number.
	Page int32 `json:"page,omitempty"`

	// Optional enumerator. You can assign the mode of implementation of where criterions by using AND and OR types under whereType parameter.
	WhereType string `json:"whereType,omitempty"`

	Where []WhereItem `json:"where,omitempty"`

	Order ListOrder `json:"order,omitempty"`
}
