/* 
 * Switch Database REST API
 *
 * Switch API is the primary endpoint of data sevices and Switch DB's platform. You can do adding, editing, deleting or listing data works to your database with query operations by using this low-level API based on HTTP.
 *
 * OpenAPI spec version: 1.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type WhereItem struct {

	// You can explain the controls of more than one state with where. The controls of states: equal, notEqual, like, greaterThan, lessThan
	Type_ string `json:"type,omitempty"`

	// Column name
	Column string `json:"column,omitempty"`

	// Column value
	Value string `json:"value,omitempty"`
}
